const products = [
  {
    id: 1,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Acer Aspire 3 A315-59 Intel Core i5-1235U 16Gb RAM 512GB SSD 15.6inc FullHD Win11",
    description:
      "Laptop is fully refurbished by Acer, as new condition. 12 months Acer warranty. Win11 Home 64-bit installed. AC adapter and power cord included.",
    slug: "acer-aspire-3-a315-59-intel-core-i5-1235u-16gb-ram-512gb-ssd-15-6inc-fullhd-win11",
    startPrice: 400.0,
    stepPrice: 20.0,
    buyNowPrice: 800.0,
    currentPrice: 400.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 2,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports) i7 1.7 GHz 16 GB Ram",
    description:
      "Used 2020 Macbook Pro. USB charging cable not included. Still in great condition, very little cosmetic wear and tear. Runs well!",
    slug: "macbook-pro-13-inch-2020-two-thunderbolt-3-ports-i7-1-7-ghz-16-gb-ram",
    startPrice: 550.0,
    stepPrice: 20.0,
    buyNowPrice: 900.0,
    currentPrice: 550.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 3,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Microsoft Surface Pro 7+ Intel i5 1135G7 2.40GHz 8GB RAM 256GB SSD 12.3inch Win 11",
    description:
      "Good - Refurbished: The item shows moderate wear and is backed by a one year warranty. It is fully functional and has been professionally refurbished, inspected and cleaned to good condition by qualified sellers. The item includes original or new accessories and will come in a new generic packaging. See the seller's listing for full details.",
    slug: "microsoft-surface-pro-7-plus-intel-i5-1135g7-2-40ghz-8gb-ram-256gb-ssd-12-3inch-win-11",
    startPrice: 400.0,
    stepPrice: 20.0,
    buyNowPrice: 700.0,
    currentPrice: 400.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 4,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Acer Nitro 5 AN517-51 Gaming Laptop 17.3inch 16gb RAM 256gb SSD",
    description:
      "About 4 years old, used but still works well and runs games fine. Selling as I’ve upgraded. Comes with original charger. No original box.",
    slug: "acer-nitro-5-an517-51-gaming-laptop-17-3inch-16gb-ram-256gb-ssd",
    startPrice: 200.0,
    stepPrice: 20.0,
    buyNowPrice: 360.0,
    currentPrice: 200.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 5,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "NEW Acer Predator Helios Neo 14.5inch Gaming Laptop Ultra 7-155H 16GB 1Tb RTX 4070",
    description:
      "The Acer Predator Helios Neo 14.5inch Gaming Laptop Ultra 7-155H is a high-performance gaming laptop designed for gaming enthusiasts. With an ultra 7-155H processor, NVIDIA GeForce RTX 4070 graphics card, and 16GB of RAM, this laptop provides lightning-fast gaming experiences.",
    slug: "acer-predator-helios-neo-14-5inch-gaming-laptop-ultra-7-155h-16gb-1tb-rtx-4070",
    startPrice: 600.0,
    stepPrice: 20.0,
    buyNowPrice: 1000.0,
    currentPrice: 600.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 6,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Original Headphones Earphones with Mic for Samsung Galaxy S6 Edge",
    description:
      "This item work only 3.5mm. Listen to your favorite MP3 in stereo, and never miss a call! (unless you want to).",
    slug: "original-headphones-earphones-with-mic-for-samsung-galaxy-s6-edge",
    startPrice: 4.0,
    stepPrice: 2.0,
    buyNowPrice: 10.0,
    currentPrice: 4.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 7,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Sony - WH-CH720N Wireless Noise Canceling Headphones - Blue",
    description:
      "Sony WH-CH720N Noise Canceling Wireless Headphones Bluetooth Over The Ear Headset with Microphone and Alexa Built-in",
    slug: "sony-wh-ch720n-wireless-noise-canceling-headphones-blue",
    startPrice: 20.0,
    stepPrice: 5.0,
    buyNowPrice: 60.0,
    currentPrice: 20.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 8,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Bose Solo Soundbar 2 Home Theater, Certified Refurbished",
    description:
      "The item is in a pristine, like-new condition. It has been professionally inspected, cleaned, and restored by the manufacturer. The item will be in new packaging with original or new accessories.",
    slug: "bose-solo-soundbar-2-home-theater-certified-refurbished",
    startPrice: 40.0,
    stepPrice: 5.0,
    buyNowPrice: 100.0,
    currentPrice: 40.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 9,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Rockville PEN-80T BLACK 8inch 70V 40W Hanging Pendant Speaker Commercial/Restaurant",
    description:
      "Rockville PEN-80T Black 8inch 70V Commercial Pendant Speaker – Superior Sound for Higher Ceilings Transform your restaurant, retail space, or commercial venue with the Rockville PEN-80T 8inch Hanging Pendant Speaker.",
    slug: "rockville-pen-80t-black-8inch-70v-40w-hanging-pendant-speaker-commercial-restaurant",
    startPrice: 50.0,
    stepPrice: 5.0,
    buyNowPrice: 120.0,
    currentPrice: 50.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 10,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Astrox 100zx 4UG5 badminton racket in excellent condition",
    description:
      "Used: An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used.",
    slug: "astrox-100zx-4ug5-badminton-racket-in-excellent-condition",
    startPrice: 80.0,
    stepPrice: 10.0,
    buyNowPrice: 230.0,
    currentPrice: 80.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 11,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "ASTROX 88S Badminton Racket",
    description:
      "Used: An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used.",
    slug: "astrox-88s-badminton-racket",
    startPrice: 40.0,
    stepPrice: 10.0,
    buyNowPrice: 100.0,
    currentPrice: 40.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 12,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Badminton Shuttlecocks Tube of 6 Pcs Nylon Feathers Yellow/White 3 Speeds Raquex",
    description:
      "New: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.",
    slug: "badminton-shuttlecocks-tube-of-6-pcs-nylon-feathers-yellow-white-3-speeds-raquex",
    startPrice: 3.0,
    stepPrice: 1.0,
    buyNowPrice: 10.0,
    currentPrice: 3.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 13,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Yonex Power Cushion 65 Badminton Tennis Shoes White Black Yellow Men's Size 10",
    description:
      "Yonex Power Cushion athletic shoes in white black and yellow. Designed for high-performance sports with excellent support and cushioning. Ideal for badminton or indoor court sports. Non-marking soles.",
    slug: "yonex-power-cushion-65-badminton-tennis-shoes-white-black-yellow-mens-size-10",
    startPrice: 30.0,
    stepPrice: 2.0,
    buyNowPrice: 70.0,
    currentPrice: 3.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 14,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "YONEX 25F/W Unisex Badminton T-Shirts Korean Edition Casual [US:XXS] 259TS012U",
    description:
      "Industrial corn-based plant-derived material. It is an eco-friendly fiber material with sustainable elasticity and durability.",
    slug: "yonex-25fw-unisex-badminton-t-shirts-korean-edition-casual-usxxs-259ts012u",
    startPrice: 20.0,
    stepPrice: 5.0,
    buyNowPrice: 65.0,
    currentPrice: 20.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 15,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "3 Barca O Barcelona football shirt 80s 90s Kappa signed one",
    description:
      "Used: An item that has been used previously. The item may have some signs of cosmetic wear, but is fully operational and functions as intended. This item may be a floor model or store return that has been used.",
    slug: "3-barca-o-barcelona-football-shirt-80s-90s-kappa-signed-one",
    startPrice: 50.0,
    stepPrice: 10.0,
    buyNowPrice: 150.0,
    currentPrice: 50.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 16,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "New Men'S Football Boots Ultralight Non-Slip Sport Indoor Soccer Shoes Non Slip",
    description:
      "New: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.",
    slug: "new-mens-football-boots-ultralight-non-slip-sport-indoor-soccer-shoes-non-slip",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 36.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 17,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "2025 Parkside NWSL Pacific Pick From List! Signatures Series! AUTO",
    description:
      "New: A brand-new, unused, unopened, undamaged item in its original packaging (where packaging is applicable). Packaging should be the same as what is found in a retail store, unless the item is handmade or was packaged by the manufacturer in non-retail packaging, such as an unprinted box or plastic bag.",
    slug: "2025-parkside-nwsl-pacific-pick-from-list-signatures-series-auto",
    startPrice: 20.0,
    stepPrice: 2.0,
    buyNowPrice: 50.0,
    currentPrice: 20.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 18,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Paul Pogba Juventus 2015/16 Away Jersey – Pink (10, Size L)",
    description:
      "Paul Pogba Juventus 2015/16 Away Jersey – Pink (10, Size L) in Excellent Condition. Worn only a few times, this jersey is perfect for any Juventus fan or collector. Made from high-quality materials, it features the iconic pink colorway and Pogba's number 10 on the back. Don't miss out on this rare find!",
    slug: "paul-pogba-juventus-2015-16-away-jersey-pink-10-size-l",
    startPrice: 20.0,
    stepPrice: 5.0,
    buyNowPrice: 70.0,
    currentPrice: 20.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 19,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "JOOLA Andre Agassi Pro Pickleball Paddle 16mm （Free Shipping）",
    description:
      "JOOLA Andre Agassi Pro Pickleball Paddle 16mm in Excellent Condition. This paddle offers superior control and power, perfect for both beginners and advanced players. Enjoy free shipping on this high-quality paddle. Don't miss out on this great deal!",
    slug: "joola-andre-agassi-pro-pickleball-paddle-16mm-free-shipping",
    startPrice: 40.0,
    stepPrice: 5.0,
    buyNowPrice: 110.0,
    currentPrice: 40.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 20,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Nike Zoom Challenge Pickleball Shoes Black White Athletic Shoes Size 9）",
    description:
      "Nike Zoom Challenge Pickleball Shoes in Excellent Condition. These shoes provide excellent support and comfort for pickleball players of all levels. Featuring a stylish black and white design, size 9. Don't miss out on this great deal!",
    slug: "nike-zoom-challenge-pickleball-shoes-black-white-athletic-shoes-size-9",
    startPrice: 10.0,
    stepPrice: 5.0,
    buyNowPrice: 55.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 21,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "JOOLA Ben Johns Perseus Pro lV GUAVA RUSH 16mm Pickleball Paddle-With Cover",
    description:
      "JOOLA Ben Johns Perseus Pro lV GUAVA RUSH 16mm Pickleball Paddle in Excellent Condition. This paddle offers superior control and power, perfect for both beginners and advanced players. Comes with a protective cover. Don't miss out on this great deal!",
    slug: "joola-ben-johns-perseus-pro-lv-guava-rush-16mm-pickleball-paddle-with-cover",
    startPrice: 50.0,
    stepPrice: 5.0,
    buyNowPrice: 125.0,
    currentPrice: 50.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 22,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Prince Pickleball Pleated Dress Tennis White Green Sleeveless Collared Size XL",
    description:
      "Prince Pickleball Pleated Dress Tennis White Green Sleeveless Collared Size XL in Excellent Condition. This dress offers superior comfort and style, perfect for both casual and competitive play. Don't miss out on this great deal!",
    slug: "prince-pickleball-pleated-dress-tennis-white-green-sleeveless-collared-size-xl",
    startPrice: 4.0,
    stepPrice: 1.0,
    buyNowPrice: 20.0,
    currentPrice: 4.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 23,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "PHILLIPS-MOORE NINJA 30% MORE POWER & SPIN BLACKOUT EDITION",
    description:
      "PHILLIPS-MOORE NINJA 30% MORE POWER & SPIN BLACKOUT EDITION in Excellent Condition. This paddle offers superior control and power, perfect for both beginners and advanced players. Don't miss out on this great deal!",
    slug: "phillips-moore-ninja-30-more-power-spin-blackout-edition",
    startPrice: 300.0,
    stepPrice: 20.0,
    buyNowPrice: 600.0,
    currentPrice: 300.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 24,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Adidas Tennis HU Pharrell White Green Shoe Sneakers Mens Size US5 UK4.5 EU37 1/3",
    description:
      "Adidas Tennis HU Pharrell White Green Shoe Sneakers Mens Size US5 UK4.5 EU37 1/3 in Excellent Condition. These sneakers offer superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "adidas-tennis-hu-pharrell-white-green-shoe-sneakers-mens-size-us5-uk4-5-eu37-1-3",
    startPrice: 80.0,
    stepPrice: 5.0,
    buyNowPrice: 180.0,
    currentPrice: 80.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 25,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Head Gravity Pro 2023 Tennis Racquet Grip Size 4 3/8",
    description:
      "Head Gravity Pro 2023 Tennis Racquet Grip Size 4 3/8 in Excellent Condition. This racquet offers superior control and power, perfect for both beginners and advanced players. Don't miss out on this great deal!",
    slug: "head-gravity-pro-2023-tennis-racquet-grip-size-4-3-8",
    startPrice: 60.0,
    stepPrice: 5.0,
    buyNowPrice: 100.0,
    currentPrice: 60.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 26,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "ADIDAS Women's Climachill® Tennis Tank Top",
    description:
      "ADIDAS Women's Climachill® Tennis Tank Top in Excellent Condition. This tank top offers superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "adidas-womens-climachill-tennis-tank-top",
    startPrice: 2.0,
    stepPrice: 1.0,
    buyNowPrice: 12.0,
    currentPrice: 2.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 27,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Men Long sleeve Pleated Raglan Muscle Tops Slim Casual Pullover T-shirt Blouse",
    description:
      "Men Long sleeve Pleated Raglan Muscle Tops Slim Casual Pullover T-shirt Blouse in Excellent Condition. This blouse offers superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "men-long-sleeve-pleated-raglan-muscle-tops-slim-casual-pullover-t-shirt-blouse",
    startPrice: 4.0,
    stepPrice: 1.0,
    buyNowPrice: 23.0,
    currentPrice: 4.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 28,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Mens Slimming Body Shaper Belly Chest Compression Vest Girdle T-Shirt Tank Top",
    description:
      "Mens Slimming Body Shaper Belly Chest Compression Vest Girdle T-Shirt Tank Top in Excellent Condition. This tank top offers superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "mens-slimming-body-shaper-belly-chest-compression-vest-girdle-t-shirt-tank-top",
    startPrice: 1.0,
    stepPrice: 1.0,
    buyNowPrice: 6.0,
    currentPrice: 1.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 29,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Mizuno logo funny T-Shirt Size S-5XL Made in USA",
    description:
      "Mizuno logo funny T-Shirt Size S-5XL Made in USA in Excellent Condition. This t-shirt offers superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "mizuno-logo-funny-t-shirt-size-s-5xl-made-in-usa",
    startPrice: 4.0,
    stepPrice: 2.0,
    buyNowPrice: 26.0,
    currentPrice: 4.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 30,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Women Long Sleeve Shirt Dress with Belt Pleated Frill Swing Midi Elegant Fashion",
    description:
      "Women Long Sleeve Shirt Dress with Belt Pleated Frill Swing Midi Elegant Fashion in Excellent Condition. This dress offers superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "women-long-sleeve-shirt-dress-with-belt-pleated-frill-swing-midi-elegant-fashion",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 36.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 31,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "NEW Womens Longline Denim Shirt Dress Ladies Jean Dresses Size 8 10 12 14",
    description:
      "NEW Womens Longline Denim Shirt Dress Ladies Jean Dresses Size 8 10 12 14 in Excellent Condition. This dress offers superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "new-womens-longline-denim-shirt-dress-ladies-jean-dresses-size-8-10-12-14",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 24.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 32,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Womens Tee Shirts Fall Baggy Tops Long Sleeve Crew Neck Shirts Sweatshirt",
    description:
      "Womens Tee Shirts Fall Baggy Tops Long Sleeve Crew Neck Shirts Sweatshirt in Excellent Condition. This shirt offers superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "womens-tee-shirts-fall-baggy-tops-long-sleeve-crew-neck-shirts-sweatshirt",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 30.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 33,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Victorious Men's Essential Loose Fit Baggy Wide Denim Jeans Pants DL999EY",
    description:
      "Victorious Men's Essential Loose Fit Baggy Wide Denim Jeans Pants DL999EY in Excellent Condition. These jeans offer superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "victorious-mens-essential-loose-fit-baggy-wide-denim-jeans-pants-dl999ey",
    startPrice: 14.0,
    stepPrice: 2.0,
    buyNowPrice: 38.0,
    currentPrice: 14.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 34,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Men's Fleece Casual Sports Track Pants w Zip Pocket Striped Sweat Trousers S-6XL",
    description:
      "Men's Fleece Casual Sports Track Pants w Zip Pocket Striped Sweat Trousers S-6XL in Excellent Condition. These pants offer superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "mens-fleece-casual-sports-track-pants-w-zip-pocket-striped-sweat-trousers-s-6xl",
    startPrice: 4.0,
    stepPrice: 1.0,
    buyNowPrice: 15.0,
    currentPrice: 4.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 35,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Men's Kam Heavyweight Cargo Pants Relaxed Fit Trousers with Multi Pockets 40-60",
    description:
      "Men's Kam Heavyweight Cargo Pants Relaxed Fit Trousers with Multi Pockets 40-60 in Excellent Condition. These pants offer superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "mens-kam-heavyweight-cargo-pants-relaxed-fit-trousers-with-multi-pockets-40-60",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 30.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 36,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Enzo Womens Skinny Stretch Jeans Ladies Denim Slim Fit Pants UK Size 6-26",
    description:
      "Enzo Womens Skinny Stretch Jeans Ladies Denim Slim Fit Pants UK Size 6-26 in Excellent Condition. These pants offer superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "enzo-womens-skinny-stretch-jeans-ladies-denim-slim-fit-pants-uk-size-6-26",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 24.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 37,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Women's High-Waisted Woolen Pencil Pants – Winter Casual Suit Trousers with Pock",
    description:
      "Women's High-Waisted Woolen Pencil Pants – Winter Casual Suit Trousers with Pockets in Excellent Condition. These pants offer superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "womens-high-waisted-woolen-pencil-pants-winter-casual-suit-trousers-with-pockets",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 22.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
  {
    id: 38,
    sellerId: 1, // Mock seller ID
    categoryId: 1, // Mock category ID
    winnerId: null,
    name: "Women Winter Drawstring Trousers Pants Quilted Padded Loose Outdoor Ski Warm",
    description:
      "Women Winter Drawstring Trousers Pants Quilted Padded Loose Outdoor Ski Warm in Excellent Condition. These pants offer superior comfort and style, perfect for both casual and athletic wear. Don't miss out on this great deal!",
    slug: "women-winter-drawstring-trousers-pants-quilted-padded-loose-outdoor-ski-warm",
    startPrice: 10.0,
    stepPrice: 2.0,
    buyNowPrice: 34.0,
    currentPrice: 10.0,
    postDate: "",
    endDate: "2025-02-05T10:00:00.000Z",
    isAutoExtend: true,
    isInstantPurchase: true,
    isNew: true,
    status: "active",
    minImages: 3,
  },
];
